[package]
name = "vscode-generator"
version = "0.1.0"
edition = "2021"

[features]
rust = []

[dependencies]
chrono = "0.4.38"
md5 = "0.7.0"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.120"
